### ISSUE TITLE
Map-Image

### ISSUE THREAD

**Issue by Millennium-Heap** [Millennium-Heap/geo-locator#3]
# Description
This phase involves, rendering a map-image file that shows the approximate geolocation of the device running the code along with a radius of accuracy displayed in the map-image.

## Sub-Feature
- Map-Image REST API by HERE location services.
- Download file service via web-client.
- Default application opener for the image file.

## Examples (Optional)
![image](https://user-images.githubusercontent.com/78008633/106309223-d1820c00-6287-11eb-802e-01629f90cd60.png)

## Dependencies
- GeoCoordinate watcher

## Milestones
- [x] Connect the map-image REST API by HERE location services.
- [x] Develop a process to download a map-image file.
- [x] Develop a method to open the image file by default

## Member/Members (@Github-Handle) (@Email-Id)
- Millennium Singha (@Millennium-Heap) (millenniumsingha@gmail.com)
